services:
  postgres:
    image: postgres:16-alpine
    container_name: tenpo-postgres
    environment:
      POSTGRES_DB: tenpo_challenge
      POSTGRES_USER: tenpo
      POSTGRES_PASSWORD: tenpo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenpo -d tenpo_challenge"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenpo-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tenpo_challenge
      SPRING_DATASOURCE_USERNAME: tenpo
      SPRING_DATASOURCE_PASSWORD: tenpo
    ports:
      - "8080:8080"

volumes:
  postgres_data:
